-- =========================
-- ROLES TABLE
-- =========================

CREATE TABLE IF NOT EXISTS public.roles (
                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY
(INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE)
    NOT NULL,
    name VARCHAR(50) NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT roles_name_key UNIQUE (name)
    );

-- =========================
-- USERS TABLE
-- =========================

CREATE TABLE IF NOT EXISTS public.users (
                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY
(INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE)
    NOT NULL,
    telegram_id BIGINT NOT NULL,
    username VARCHAR(255),
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    role_id BIGINT,
    status VARCHAR(16) NOT NULL,

    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_telegram_id_key UNIQUE (telegram_id),
    CONSTRAINT fk_users_role
    FOREIGN KEY (role_id)
    REFERENCES public.roles(id)
    ON UPDATE CASCADE
    ON DELETE SET NULL
    );

-- =========================
-- INDEXES
-- =========================

CREATE INDEX IF NOT EXISTS idx_users_status
    ON public.users USING btree (status);



CREATE TABLE IF NOT EXISTS roles (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR(50) NOT NULL UNIQUE
    );

INSERT INTO roles (name) VALUES ('ADMIN') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('USER')  ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('SUPER_ADMIN')  ON CONFLICT DO NOTHING;