-- =========================
-- INVITATION TABLE
-- =========================

CREATE TABLE IF NOT EXISTS public.invitation (
                                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY
                                                 PRIMARY KEY,

                                                 invitation VARCHAR(255) NOT NULL,

    is_used CHAR(1) NOT NULL DEFAULT 'N'
    CONSTRAINT chk_invitation_is_used
    CHECK (is_used IN ('Y', 'N')),

    user_id BIGINT
    CONSTRAINT fk_invitation_user
    REFERENCES public.users(id)
    ON DELETE SET NULL,

    used_at TIMESTAMP,

    target_role VARCHAR(20) NOT NULL,

    expires_at TIMESTAMP NOT NULL,

    created_by BIGINT
    CONSTRAINT fk_invitation_created_by
    REFERENCES public.users(id)
    ON DELETE SET NULL
    );

-- =========================
-- INDEXES
-- =========================

CREATE INDEX IF NOT EXISTS idx_invitation_expires_at
    ON public.invitation (expires_at);

CREATE INDEX IF NOT EXISTS idx_invitation_created_by
    ON public.invitation (created_by);
